<a href="https://colab.research.google.com/github/adarshs002/numpy_mini_project/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MINI PROJECT

**Step 1 : Read the Data!**

In [30]:
import numpy as np
data = np.genfromtxt('/content/makeSenseOfCensus.csv', delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [31]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


**Step 2 : Append the Data**

In [32]:
import numpy as np
new_record = np.array([[50, 9, 4, 1, 0, 0, 40, 0]])
concatenated_data = np.concatenate((data, new_record), axis = 0)
print(concatenated_data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


**Step 3 : Check if it's a young country or old country**

In [33]:
age = (concatenated_data[:,0])
print(age)
print("--------------------------")
max_age = age.max()
print("MAXIMUM AGE",max_age)
print("--------------------------")
min_age = age.min()
print("MINIMUM AGE",min_age)
print("--------------------------")
age_mean = age.mean()
print("MEAN AGE",age_mean)
print("--------------------------")
age_std = np.std(age)
print("STANDARD DEVIATION",age_std)


[39. 50. 38. ... 40. 39. 50.]
--------------------------
MAXIMUM AGE 90.0
--------------------------
MINIMUM AGE 17.0
--------------------------
MEAN AGE 38.06293706293706
--------------------------
STANDARD DEVIATION 13.341478176165857


**Step 4: Let's check the country's race distribution to identify the minorities**

In [34]:
race = concatenated_data[:,2]
race_0 = race[race == 0]
print(race_0)
print("--------------------------")
race_1 = race[race == 1]
print(race_1)
print("--------------------------")
race_2 = race[race == 2]
print(race_2)
print("--------------------------")
race_3 = race[race == 3]
print(race_3)
print("--------------------------")
race_4 = race[race == 4]
print(race_4)
print("--------------------------")
print("-----------CHECKING TEH LENGTH-------------")
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

print("race_0 : ",len_0)
print("race_1 : ",len_1)
print("race_2 : ",len_2)
print("race_3 : ",len_3)
print("race_4 : ",len_4)

l = []
l.append(len_0)
l.append(len_1)
l.append(len_2)
l.append(len_3)
l.append(len_4)
# print(l)
# print(len_0)
minority_race = min(l)
if len_0 == minority_race:
  print("race with the minimum no. of citizens is race_0")
elif len_1 == minority_race:
  print("race with the minimum no. of citizens is race_1") 
elif len_2 == minority_race:
  print("race with the minimum no. of citizens is race_1")
elif len_3 == minority_race:
  print("race with the minimum no. of citizens is race_3")
elif len_4 == minority_race:
  print("race with the minimum no. of citizens is race_4")   
print("MINORITY RACE :  ", minority_race)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
--------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
--------------------------
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
--------------------------
[3. 3. 3. 3. 3. 3.]
--------------------------
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 

**Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place** 

In [35]:
senior_citizens = age[age>60]

print("SENIOR CITIZENS : ", senior_citizens)
print("--------------------------")
senior_working_hours = concatenated_data[:,6]
a = senior_working_hours[age>60]
print("Senior Citizen Working hours", a)
working_hours_sum = a.sum()
print("--------------------------")
print("Sum of Working Huours of Seniors:",working_hours_sum)
senior_citizens_len = len(senior_citizens)
print("Length of Senior Citizens:", senior_citizens_len )
average_working_hours = working_hours_sum/senior_citizens_len
print("Average working hours of Senior Citizens: ", average_working_hours)

SENIOR CITIZENS :  [79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]
--------------------------
Senior Citizen Working hours [20.  2. 40. 40. 40. 40.  2. 20. 20. 40. 40. 50. 20. 40. 40. 40. 16. 40.
 24. 10. 45. 55.  8. 40. 40. 40. 24. 24. 35. 20. 40.  9. 48. 40. 40. 30.
 24. 15. 15.  4. 59. 50. 40. 20. 40. 45. 40. 40. 24.  6. 48. 40. 40. 15.
 55. 40. 30.  5. 40. 40. 20.]
--------------------------
Sum of Working Huours of Seniors: 1917.0
Length of Senior Citizens: 61
Average working hours of Senior Citizens:  31.42622950819672


**Step 6: Let's check that higher educated people have better pay in general.**

In [45]:
education_num = concatenated_data[:,1]
print("EDUCATED PEOPLE : " ,education_num)
print("--------------------------")
high = education_num[education_num > 10]
print("HIGH", high)
print("--------------------------")
low = education_num[education_num <= 10]
print("LOW", low)
print("--------------------------")
a1 = concatenated_data[:, 7]
high_income = a1[education_num > 10]
print("avg_pay_high : ",high_income.mean())
print("--------------------------")
low_income = a1[education_num <= 10]
print("avg_pay_low : ",low_income.mean())

EDUCATED PEOPLE :  [13. 13.  9. ... 10. 13.  9.]
--------------------------
HIGH [13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13